"""absensi_add_lokasi_gps

Revision ID: 6aeb15828878
Revises: aca187d4e25e
Create Date: 2024-12-30 14:47:32.569496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6aeb15828878'
down_revision: Union[str, None] = 'aca187d4e25e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('absensi', sa.Column('jam_masuk', sa.Time(), nullable=True))
    op.add_column('absensi', sa.Column('jam_keluar', sa.Time(), nullable=True))
    op.add_column('absensi', sa.Column('lokasi_masuk', sa.String(), nullable=True))
    op.add_column('absensi', sa.Column('lokasi_keluar', sa.String(), nullable=True))
    op.drop_column('absensi', 'jam_absen_masuk')
    op.drop_column('absensi', 'jam_absen_keluar')
    op.drop_column('absensi', 'lokasi')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('absensi', sa.Column('lokasi', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('absensi', sa.Column('jam_absen_keluar', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('absensi', sa.Column('jam_absen_masuk', postgresql.TIME(), autoincrement=False, nullable=True))
    op.drop_column('absensi', 'lokasi_keluar')
    op.drop_column('absensi', 'lokasi_masuk')
    op.drop_column('absensi', 'jam_keluar')
    op.drop_column('absensi', 'jam_masuk')
    # ### end Alembic commands ###
