name: Deploy

on:
  push:
    branches:
      - master

  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        env:
          APP_PATH: ${{ secrets.APP_PATH }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: APP_PATH
          script: |
            cd $APP_PATH
            sudo git pull
            sudo docker-compose down
            sudo docker-compose up -d --build
